name: opencv_dart
description: "OpenCV4 bindings for Dart language and Flutter, using dart:ffi. The most complete OpenCV bindings for Dart! With asynchronous support now!"
version: 1.2.2
homepage: https://github.com/rainyl/opencv_dart

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  ffi: ^2.1.3
  path: ^1.9.0
  args: ^2.5.0
  archive: ^3.6.1
  stack_trace: ^1.11.1

dev_dependencies:
  ffigen: ^13.0.0
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      ios:
        ffiPlugin: true
