name: opencv_dart
description: "OpenCV4 bindings for Dart language and Flutter, using dart:ffi. The most complete OpenCV bindings for Dart!"
version: 1.0.0+2
binary_version: 1.0.0+2
homepage: https://github.com/rainyl/opencv_dart

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  ffi: ^2.1.0
  equatable: ^2.0.5
  yaml: ^3.1.2
  path: ^1.9.0
  args: ^2.4.2
  archive: ^3.4.10

dev_dependencies:
  ffigen: ^11.0.0
  flutter_lints: ^3.0.1
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      ios:
        ffiPlugin: true
