name: dartcv4
description: "OpenCV4 bindings for Dart language and Flutter, using dart:ffi. The most complete OpenCV bindings for Dart!"
version: 2.1.0-dev.3
homepage: https://github.com/rainyl/opencv_dart

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  code_assets: ^0.19.5
  data_assets: ^0.19.2
  ffi: ^2.1.3
  hooks: ^0.20.0
  logging: ^1.2.0
  native_toolchain_cmake: ^0.1.0
  # native_toolchain_cmake:
  #   path: ../native_toolchain_cmake
  path: ^1.9.0
  yaml: ^3.1.3

dev_dependencies:
  ffigen: ^19.0.0
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter

hooks:
  user_defines:
    dartcv4:
      include_modules:
        - calib3d
        - contrib
        - dnn
        - features2d
        - highgui
        - imgcodecs
        - imgproc
        - objdetect
        - photo
        - stitching
        - video
        - videoio
