name: dartcv4
description: "OpenCV4 bindings for Dart language and Flutter, using dart:ffi. The most complete OpenCV bindings for Dart!"
version: 2.1.0-dev.0
homepage: https://github.com/rainyl/opencv_dart

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  ffi: ^2.1.3
  path: ^1.9.0
  native_assets_cli: ^0.11.0
  logging: ^1.2.0
  native_toolchain_c: ^0.8.0
  native_toolchain_cmake: ^0.0.1

dev_dependencies:
  ffigen: ^16.1.0
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter
