name: opencv_dart
description: "OpenCV4 bindings for Dart language and Flutter, using dart:ffi. The most complete OpenCV bindings for Dart!"
version: 1.0.5+1
binary_version: 1.0.5
homepage: https://github.com/rainyl/opencv_dart

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  ffi: ^2.1.0
  equatable: ^2.0.5
  yaml: ^3.1.2
  path: ^1.9.0
  args: ^2.5.0
  archive: ^3.5.1
  stack_trace: ^1.11.1

dev_dependencies:
  ffigen: ^12.0.0
  flutter_lints: ^4.0.0
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      ios:
        ffiPlugin: true
