name: opencv_dart
description: |
  OpenCV4 bindings for Flutter, using dart:ffi.
version: 2.1.0
opencv_version: 4.12.0.0
dartcv_version: 4.12.0.2
repository: https://github.com/rainyl/opencv_dart
homepage: https://github.com/rainyl/opencv_dart/tree/main/packages/opencv_dart

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  dartcv4: 2.1.0+1
  # dartcv4:
  #   path: ../dartcv

dev_dependencies:
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter
