name: opencv_dart
description: |
  OpenCV4 bindings for Flutter, using dart:ffi.
version: 1.4.4
opencv_version: 4.12.0.0
dartcv_version: 4.12.0.1
repository: https://github.com/rainyl/opencv_dart
homepage: https://github.com/rainyl/opencv_dart/tree/main/packages/opencv_dart

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartcv4: 1.1.7
  # dartcv4:
  #   path: ../dartcv

dev_dependencies:
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      ios:
        ffiPlugin: true
