name: dartcv4
description: "OpenCV4 bindings for Dart language and Flutter, using dart:ffi. The most complete OpenCV bindings for Dart!"
version: 2.2.1+1
opencv_version: 4.13.0
homepage: https://github.com/rainyl/opencv_dart

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  hooks: ^1.0.0
  logging: ^1.3.0
  native_toolchain_cmake: ^0.2.3
  # native_toolchain_cmake:
  #   path: ../native_toolchain_cmake

dev_dependencies:
  ffigen: ^20.1.1
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter

hooks:
  user_defines:
    # this is for development and debug, not seen in production
    dartcv4:
      debug: true
      linux:
        generator: "Unix Makefiles"
      macos:
        generator: Ninja
      android:
        generator: Ninja
      ios:
        generator: Xcode
      include_modules:
        - calib3d
        - contrib
        - dnn
        - features2d
        - freetype
        - highgui
        - imgcodecs
        - imgproc
        - objdetect
        - photo
        - stitching
        - video
        - videoio
        - aruco
        - img_hash
        - quality
        - wechat_qrcode
        - ximgproc
        - xobjdetect
