name: dart_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dartcv4:
    path: ../../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
