name: opencv_core
description: |
  OpenCV4 bindings for Flutter.
  This plugin does NOT include `highgui` and `videoio`,
  if you need them, please use `opencv_dart` instead.
version: 1.3.5
opencv_version: 4.11.0+0
dartcv_version: 4.11.0.0
repository: https://github.com/rainyl/opencv_dart
homepage: https://github.com/rainyl/opencv_dart/tree/main/packages/opencv_core

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartcv4: ^1.1.1

dev_dependencies:
  test: ^1.25.2

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
